export const mapUnavailableContent = {
  connection: {
    alertVariant: 'error',
    badgeVariant: 'error',
    badge: 'Connection issue',
    title: 'Map data is unavailable',
    message: 'We cannot connect to RapidAIM map data right now, and our team has been alerted.',
    detail: 'We are checking the map service and RapidAIM database, and aim to restore access shortly.',
    primaryAction: 'Retry connection',
    secondaryAction: 'Contact support',
    detailsTitle: 'Connection issue details',
    details: [
      'The dashboard could not load blocks, sensors, or recent detections.',
      'If this continues, contact support with the error reference shown in the dashboard so the team can investigate quickly.',
    ],
  },
  onboarding: {
    alertVariant: 'info',
    badgeVariant: 'info',
    badge: 'Setup in progress',
    title: 'Your map is being prepared',
    message: 'Your account is active, and setup is underway.',
    detail: 'Blocks and sensors usually appear within 1-3 days once the onboarding team has linked your account data.',
    primaryAction: '',
    secondaryAction: 'Contact support',
    detailsTitle: 'Setup in progress details',
    details: [
      'This state is expected for newly onboarded users before block and sensor records are assigned.',
      'You can keep using account settings while the onboarding team completes setup, which usually takes 1-3 days.',
    ],
  },
  waitingForData: {
    alertVariant: 'warning',
    badgeVariant: 'warning',
    badge: 'Waiting for data',
    title: 'Waiting for field data',
    message: 'Your blocks and sensors are set up, but recent detections have not arrived yet.',
    detail: 'New information can take up to 7 days to appear after setup or sensor changes.',
    primaryAction: '',
    dismissAction: 'Dismiss',
    secondaryAction: 'Contact support',
    resumeAction: 'Review message',
    detailsTitle: 'Waiting for data details',
    details: [
      'The map can show your setup before live detections are available.',
      'If no data appears after 7 days, contact support so the team can check sensor sync and database status.',
    ],
  },
  paused: {
    alertVariant: 'warning',
    badgeVariant: 'warning',
    badge: 'Subscription paused',
    title: 'Live map access is paused',
    message: 'Your account information is retained, but live map access is paused until your subscription resumes.',
    detail: 'Resume your subscription to restore blocks, sensors, and detection history in the dashboard.',
    primaryAction: 'Resume subscription',
    secondaryAction: 'View account',
    detailsTitle: 'Subscription paused details',
    details: [
      'Your account has not been deleted. RapidAIM is holding your information while the subscription is paused.',
      'When billing is restored, the dashboard can reconnect your saved account data.',
    ],
  },
};
